# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('starting_semester', models.SmallIntegerField()),
                ('ending_semester', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workload', models.SmallIntegerField()),
                ('offered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('registry', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('employment_bond', models.CharField(max_length=50)),
                ('current_workload', models.SmallIntegerField()),
                ('coordinator', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Campus')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.CourseCurriculum'),
        ),
    ]
