# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_ini', models.DateField()),
                ('date_term', models.DateField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wl_week', models.SmallIntegerField()),
                ('wl_max', models.SmallIntegerField()),
                ('actv_type', models.SmallIntegerField()),
                ('comment', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=10)),
                ('addr_street', models.CharField(max_length=100)),
                ('addr_no', models.CharField(max_length=5)),
                ('addr_neighbor', models.CharField(max_length=100)),
                ('addr_city', models.CharField(max_length=100)),
                ('addr_uf', models.CharField(max_length=50)),
                ('addr_zip', models.CharField(max_length=10)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('wl_teaching', models.SmallIntegerField()),
                ('wl_extres', models.SmallIntegerField()),
                ('wl_complActv', models.SmallIntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('date_ini', models.DateField()),
                ('date_term', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('ementa', models.TextField()),
                ('block', models.SmallIntegerField()),
                ('workload', models.SmallIntegerField()),
                ('active', models.BooleanField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Area')),
                ('course_grid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.CourseGrid')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('active', models.BooleanField()),
                ('effective', models.BooleanField()),
                ('contract_term', models.DateField()),
                ('area', models.ManyToManyField(to='crud.Area')),
                ('contractType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.ContractType')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Title'),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crud.Teacher'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actv_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crud.Teacher'),
        ),
    ]
