# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_ini', models.DateField()),
                ('date_term', models.DateField()),
                ('observations', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Activity Natures',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wk_week', models.IntegerField()),
                ('wk_limit', models.IntegerField()),
                ('nature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityNature')),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=30)),
                ('add_street', models.CharField(max_length=50)),
                ('add_no', models.IntegerField()),
                ('add_neighbor', models.CharField(max_length=50)),
                ('add_city', models.CharField(max_length=50)),
                ('add_uf', models.CharField(max_length=2)),
                ('add_zip', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wk_teaching', models.IntegerField()),
                ('wk_resext', models.IntegerField()),
                ('wk_compl', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Contract Types',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Campus')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_ini', models.DateField(null=True)),
                ('date_term', models.DateField(null=True)),
                ('active', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course')),
            ],
            options={
                'verbose_name_plural': 'CourseGrids',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('ementa', models.TextField()),
                ('block', models.SmallIntegerField()),
                ('work_load', models.SmallIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Area')),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.CourseGrid')),
            ],
            options={
                'verbose_name_plural': 'Disciplines',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Discipline')),
            ],
            options={
                'verbose_name_plural': 'Enrolments',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_ini', models.DateField()),
                ('date_term', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course')),
            ],
            options={
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_ini', models.DateField()),
                ('date_term', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone1', models.CharField(max_length=14)),
                ('phone2', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
                ('efetivo', models.BooleanField()),
                ('area', models.ManyToManyField(to='crud.Area')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ContractType')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Titles',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Title'),
        ),
        migrations.AddField(
            model_name='offer',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Teacher'),
        ),
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Teacher'),
        ),
    ]
