# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='active',
            field=models.BooleanField(verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_city',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_neighbor',
            field=models.CharField(max_length=50, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_no',
            field=models.IntegerField(verbose_name='n\xfamero'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_street',
            field=models.CharField(max_length=50, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_uf',
            field=models.CharField(max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_zip',
            field=models.CharField(max_length=50, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone1',
            field=models.CharField(max_length=14, verbose_name='telefone 1'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone2',
            field=models.CharField(max_length=14, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='nome curto'),
        ),
    ]
