# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='activitynature',
            options={'verbose_name': 'Natureza da atividade', 'verbose_name_plural': 'Naturezas de atividades'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'Tipo de atividade', 'verbose_name_plural': 'Tipos de atividades'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '\xc1rea', 'verbose_name_plural': '\xc1reas'},
        ),
        migrations.AlterModelOptions(
            name='contracttype',
            options={'verbose_name': 'Tipo de contrato', 'verbose_name_plural': 'Tipos de contrato'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.AlterModelOptions(
            name='coursegrid',
            options={'verbose_name': 'Matriz curricular', 'verbose_name_plural': 'Matrizes curriculares'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Encargo', 'verbose_name_plural': 'Encargos'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Per\xedodo', 'verbose_name_plural': 'Per\xedodos'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Professor(a)', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Titula\xe7\xe3o', 'verbose_name_plural': 'Titula\xe7\xf5es'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='activity',
            field=models.ManyToManyField(to='crud.Activity', verbose_name='atividade'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityType', verbose_name='tipo de atividade'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_ini',
            field=models.DateField(verbose_name='data inicial'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_term',
            field=models.DateField(verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='observations',
            field=models.TextField(null=True, verbose_name='observa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='quantity',
            field=models.IntegerField(verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='activitynature',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityNature', verbose_name='natureza'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='wk_limit',
            field=models.IntegerField(verbose_name='carga hor\xe1ria limite'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='wk_week',
            field=models.IntegerField(verbose_name='carga hor\xe1ria semanal'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_city',
            field=models.CharField(max_length=50, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_neighbor',
            field=models.CharField(max_length=50, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_no',
            field=models.IntegerField(verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_street',
            field=models.CharField(max_length=50, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_uf',
            field=models.CharField(max_length=2, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='add_zip',
            field=models.CharField(max_length=50, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone1',
            field=models.CharField(max_length=14, verbose_name='telefone 1'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='phone2',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='short_name',
            field=models.CharField(max_length=30, verbose_name='nome curto'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='site',
            field=models.URLField(verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_compl',
            field=models.IntegerField(verbose_name='carga hor\xe1ria complementar'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_resext',
            field=models.IntegerField(verbose_name='carga hor\xe1ria de extens\xe3o'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_teaching',
            field=models.IntegerField(verbose_name='carga hor\xe1ria de ensino'),
        ),
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='nome curto'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='date_ini',
            field=models.DateField(null=True, verbose_name='data in\xedcio'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='date_term',
            field=models.DateField(null=True, verbose_name='data t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Area', verbose_name='\xe1rea'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='block',
            field=models.SmallIntegerField(verbose_name='bloco'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.CourseGrid', verbose_name='matriz curricular'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='nome curto'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='work_load',
            field=models.SmallIntegerField(verbose_name='carga hor\xe1ria'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Discipline', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer', verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Teacher', verbose_name='professor(a)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_ini',
            field=models.DateField(verbose_name='data inicial'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_term',
            field=models.DateField(verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Semester', verbose_name='per\xedodo'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_ini',
            field=models.DateField(verbose_name='data inicial'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='date_term',
            field=models.DateField(verbose_name='data final'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='area',
            field=models.ManyToManyField(to='crud.Area', verbose_name='\xe1rea'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ContractType', verbose_name='tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='efetivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone1',
            field=models.CharField(max_length=14, verbose_name='telefone 1'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone2',
            field=models.CharField(max_length=14, null=True, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Title', verbose_name='titula\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
    ]
