# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20180118_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrid',
            name='date_term',
            field=models.DateField(null=True, verbose_name='data t\xe9rmino'),
        ),
    ]
