# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20180118_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '\xc1rea', 'verbose_name_plural': '\xc1reas'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Titula\xe7\xe3o', 'verbose_name_plural': 'Titula\xe7\xf5es'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='work_load',
            field=models.SmallIntegerField(verbose_name='carga hor\xe1ria'),
        ),
    ]
