# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20180118_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Per\xedodo', 'verbose_name_plural': 'Per\xedodos'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='observations',
            field=models.TextField(verbose_name='observa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='wk_limit',
            field=models.IntegerField(verbose_name='carga hor\xe1ria limite'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='wk_week',
            field=models.IntegerField(verbose_name='carga hor\xe1ria semanal'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_compl',
            field=models.IntegerField(verbose_name='carga hor\xe1ria complementar'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_resext',
            field=models.IntegerField(verbose_name='carga hor\xe1ria de extens\xe3o'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='wk_teaching',
            field=models.IntegerField(verbose_name='carga hor\xe1ria de ensino'),
        ),
    ]
