# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20180118_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Title', verbose_name='titula\xe7\xe3o'),
        ),
    ]
