# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20180118_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityType', verbose_name='tipo de atividade'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Teacher', verbose_name='professor(a)'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ActivityNature', verbose_name='natureza'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Area', verbose_name='\xe1rea'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.CourseGrid', verbose_name='matriz curricular'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Discipline', verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Offer', verbose_name='oferta'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Teacher', verbose_name='professor(a)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Semester', verbose_name='per\xedodo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='area',
            field=models.ManyToManyField(to='crud.Area', verbose_name='\xe1rea'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ContractType', verbose_name='tipo de contrato'),
        ),
    ]
