# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_auto_20180119_1726'),
        ('crud', '0002_auto_20180119_2014'),
    ]

    operations = [
    ]
