# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_merge_20180122_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='phone2',
            field=models.CharField(max_length=14, null=True, verbose_name='telefone 2'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='date_ini',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data in\xedcio'),
        ),
        migrations.AlterField(
            model_name='coursegrid',
            name='date_term',
            field=models.DateField(blank=True, null=True, verbose_name='data t\xe9rmino'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='activity',
            field=models.ManyToManyField(blank=True, to='crud.Activity', verbose_name='atividade'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone2',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='telefone 2'),
        ),
    ]
