# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_auto_20180122_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='add_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero'),
        ),
    ]
