# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_auto_20180122_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short_name',
            field=models.CharField(default='TCC', max_length=20, verbose_name='nome curto'),
            preserve_default=False,
        ),
    ]
