# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_auto_20180122_1724'),
        ('crud', '0014_auto_20180122_1749'),
    ]

    operations = [
    ]
